package io.yak.ops.infrastructure.client.gateway;

import javax.annotation.Resource;
import io.yak.ops.application.client.port.LinkUpClientRuntimeGateway;
import io.yak.ops.engine.legacy.LegacyRestClient;
import org.springframework.stereotype.Component;

import java.util.List;
import java.util.Map;

/**
 * REST-based implementation of {@link LinkUpClientRuntimeGateway}.
 *
 * <p>This gateway delegates LinkUp runtime operations to {@link LegacyRestClient},
 * such as querying metrics, job logs, checkpoint overview, and checkpoint history.</p>
 *
 * <p>This class belongs to the engine client adapter layer. The core client module
 * only depends on {@link LinkUpClientRuntimeGateway} and does not know the
 * concrete REST implementation details.</p>
 */
@Component
public class LinkUpRestClientRuntimeGateway implements LinkUpClientRuntimeGateway {

    @Resource
    private LegacyRestClient linkUpRestClient;

    /**
     * Queries runtime metrics of the specified LinkUp client.
     *
     * @param clientId LinkUp client id
     * @return raw runtime metrics returned by LinkUp REST API
     */
    @Override
    public List<Map<String, Object>> metrics(Long clientId) {
        return linkUpRestClient.systemMonitoringInformation(clientId);
    }

    /**
     * Queries job logs from the LinkUp engine.
     *
     * @param clientId LinkUp client id
     * @param engineJobId job id generated by the LinkUp engine
     * @param format log response format, such as json or text
     * @return engine job log content
     */
    @Override
    public String jobLogs(
            Long clientId,
            String engineJobId,
            String format
    ) {
        return linkUpRestClient.jobLogs(clientId, engineJobId, format);
    }

    /**
     * Queries checkpoint overview of a LinkUp job.
     *
     * @param clientId LinkUp client id
     * @param jobId LinkUp engine job id
     * @return checkpoint overview returned by LinkUp REST API
     */
    @Override
    public Map<String, Object> checkpointOverview(
            Long clientId,
            Long jobId
    ) {
        return linkUpRestClient.checkpointOverview(clientId, jobId);
    }

    /**
     * Queries checkpoint history of a LinkUp job.
     *
     * @param clientId LinkUp client id
     * @param jobId LinkUp engine job id
     * @param pipelineId optional pipeline id
     * @param limit max history size
     * @param status optional checkpoint status filter
     * @return checkpoint history returned by LinkUp REST API
     */
    @Override
    public List<Map<String, Object>> checkpointHistory(
            Long clientId,
            Long jobId,
            Long pipelineId,
            Integer limit,
            String status
    ) {
        return linkUpRestClient.checkpointHistory(
                clientId,
                jobId,
                pipelineId,
                limit,
                status
        );
    }
}
