<?xml version='1.0' encoding='UTF-8'?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>io.yak.ops</groupId>
    <artifactId>yak-ops</artifactId>
    <version>1.0.0</version>
    <packaging>pom</packaging>
    <name>Yak Ops</name>
    <properties>
        <maven-compiler-plugin.version>3.11.0</maven-compiler-plugin.version>
        <maven-assembly-plugin.version>3.3.0</maven-assembly-plugin.version>
        <maven-release-plugin.version>2.5.3</maven-release-plugin.version>
        <maven-javadoc-plugin.version>2.10.3</maven-javadoc-plugin.version>
        <maven-source-plugin.version>2.4</maven-source-plugin.version>
        <maven-surefire-plugin.version>3.0.0-M6</maven-surefire-plugin.version>
        <maven-dependency-plugin.version>3.1.1</maven-dependency-plugin.version>
        <maven-shade-plugin.version>3.2.1</maven-shade-plugin.version>
        <exec-maven-plugin.version>3.5.0</exec-maven-plugin.version>
        <spring-boot-maven-plugin.version>2.7.18</spring-boot-maven-plugin.version>
        <maven-jar-plugin.version>3.3.0</maven-jar-plugin.version>
        <maven.compiler.source>8</maven.compiler.source>
        <maven.compiler.target>8</maven.compiler.target>
        <java.version>8</java.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <file_encoding>UTF-8</file_encoding>
        <architecture.check.skip>false</architecture.check.skip>
    </properties>

    <modules>

        <module>yak-ops-ui</module>
        <module>yak-ops-dist</module>
    </modules>

</project>
