CREATE TABLE IF NOT EXISTS yak_offline_job_definition (
    id BIGINT NOT NULL COMMENT '任务定义 ID',
    job_name VARCHAR(200) NOT NULL COMMENT '任务名称',
    job_desc VARCHAR(1000) NULL COMMENT '任务描述',
    mode VARCHAR(32) NOT NULL COMMENT 'GUIDE_SINGLE/GUIDE_MULTI/SCRIPT',
    definition_json LONGTEXT NOT NULL COMMENT '前端可编辑任务定义 JSON',
    hocon_config LONGTEXT NOT NULL COMMENT 'Link-Up HOCON 配置',
    release_state VARCHAR(16) NOT NULL DEFAULT 'OFFLINE' COMMENT 'ONLINE/OFFLINE',
    source_type VARCHAR(64) NULL COMMENT '来源数据源类型',
    sink_type VARCHAR(64) NULL COMMENT '目标数据源类型',
    source_datasource_id BIGINT NULL COMMENT '来源数据源 ID',
    sink_datasource_id BIGINT NULL COMMENT '目标数据源 ID',
    source_table TEXT NULL COMMENT '来源表或表清单 JSON',
    sink_table TEXT NULL COMMENT '目标表或表清单 JSON',
    schedule_json LONGTEXT NULL COMMENT '调度配置 JSON',
    env_json LONGTEXT NULL COMMENT '运行环境配置 JSON',
    version INT NOT NULL DEFAULT 1 COMMENT '定义版本',
    last_execution_id BIGINT NULL COMMENT '最近执行实例 ID',
    last_engine_job_id VARCHAR(128) NULL COMMENT '最近 Link-Up jobId',
    last_job_status VARCHAR(32) NULL COMMENT '最近执行状态',
    last_error_message TEXT NULL COMMENT '最近错误信息',
    last_duration_millis BIGINT NULL COMMENT '最近运行耗时毫秒',
    last_read_row_count BIGINT NULL COMMENT '最近读取行数',
    last_qps DOUBLE NULL COMMENT '最近平均 QPS',
    last_sync_bytes BIGINT NULL COMMENT '最近同步字节数',
    last_start_time DATETIME(3) NULL COMMENT '最近开始时间',
    last_end_time DATETIME(3) NULL COMMENT '最近结束时间',
    create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uk_yak_offline_job_name (job_name),
    KEY idx_yak_offline_release_state (release_state),
    KEY idx_yak_offline_job_status (last_job_status),
    KEY idx_yak_offline_update_time (update_time),
    KEY idx_yak_offline_source_datasource (source_datasource_id),
    KEY idx_yak_offline_sink_datasource (sink_datasource_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Yak Ops 离线同步任务定义';

CREATE TABLE IF NOT EXISTS yak_offline_job_execution (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '执行实例 ID',
    job_definition_id BIGINT NOT NULL COMMENT '任务定义 ID',
    engine_job_id VARCHAR(128) NULL COMMENT 'Link-Up jobId',
    status VARCHAR(32) NOT NULL COMMENT '执行状态',
    submitted_config LONGTEXT NOT NULL COMMENT '本次提交的 HOCON 快照',
    engine_snapshot_json LONGTEXT NULL COMMENT 'Link-Up 作业快照 JSON',
    error_message TEXT NULL COMMENT '错误信息',
    source_record_count BIGINT NOT NULL DEFAULT 0 COMMENT '来源读取行数',
    sink_success_record_count BIGINT NOT NULL DEFAULT 0 COMMENT '目标成功写入行数',
    source_read_bytes BIGINT NOT NULL DEFAULT 0 COMMENT '来源读取字节数',
    sink_written_bytes BIGINT NOT NULL DEFAULT 0 COMMENT '目标写入字节数',
    qps DOUBLE NOT NULL DEFAULT 0 COMMENT '平均 QPS',
    duration_millis BIGINT NOT NULL DEFAULT 0 COMMENT '运行耗时毫秒',
    create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    start_time DATETIME(3) NULL,
    end_time DATETIME(3) NULL,
    update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    KEY idx_yak_offline_execution_definition (job_definition_id, id),
    KEY idx_yak_offline_execution_engine_job (engine_job_id),
    KEY idx_yak_offline_execution_status (status),
    CONSTRAINT fk_yak_offline_execution_definition
        FOREIGN KEY (job_definition_id) REFERENCES yak_offline_job_definition (id)
        ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Yak Ops 离线同步执行实例';
