CREATE TABLE job_execution (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, instance_id BIGINT NOT NULL, attempt_no INTEGER NOT NULL, engine_type VARCHAR(64) NOT NULL, engine_endpoint_id BIGINT, external_job_id VARCHAR(255), submission_status VARCHAR(32) NOT NULL, execution_status VARCHAR(32) NOT NULL, submitting_at TIMESTAMP, submitted_at TIMESTAMP, started_at TIMESTAMP, cancelling_at TIMESTAMP, canceled_at TIMESTAMP, finished_at TIMESTAMP, last_synced_at TIMESTAMP, error_code VARCHAR(128), error_message TEXT, engine_snapshot TEXT, created_by VARCHAR(128), updated_by VARCHAR(128), create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 CONSTRAINT uk_job_execution_instance_attempt UNIQUE (instance_id, attempt_no));
CREATE INDEX idx_job_execution_external_job_id ON job_execution(external_job_id);
CREATE INDEX idx_job_execution_last_synced_at ON job_execution(last_synced_at);
CREATE INDEX idx_job_execution_status ON job_execution(execution_status);
ALTER TABLE t_baize_flow_job_instance ALTER COLUMN engine_job_id TYPE VARCHAR(255) USING engine_job_id::VARCHAR;
