<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>io.yak.ops</groupId>
        <artifactId>yak-ops-business</artifactId>
        <version>1.0.0</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>yak-ops-business-workflow</artifactId>

    <name>Yak Ops Business Workflow</name>
    <description>Workflow definition, orchestration, instances and retry business capabilities</description>

    <dependencies>
        <dependency>
            <groupId>io.yak.ops</groupId>
            <artifactId>yak-ops-core</artifactId>
        </dependency>
        <dependency>
            <groupId>io.yak.framework</groupId>
            <artifactId>yak-schedule-spring-boot-starter</artifactId>
        </dependency>
    </dependencies>
</project>
