CREATE TABLE IF NOT EXISTS yak_quality_rule (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '规则编号',
    rule_name VARCHAR(80) NOT NULL COMMENT '规则名称',
    description VARCHAR(300) NULL COMMENT '规则描述',
    importance VARCHAR(20) NOT NULL COMMENT '重要程度',
    data_source_id VARCHAR(64) NOT NULL COMMENT '数据源编号',
    data_source_name VARCHAR(128) NOT NULL COMMENT '数据源名称快照',
    catalog_name VARCHAR(128) NULL COMMENT 'Catalog 名称',
    schema_name VARCHAR(128) NULL COMMENT 'Schema 名称',
    database_name VARCHAR(128) NOT NULL COMMENT '数据库或 Schema 展示名称',
    table_name VARCHAR(256) NOT NULL COMMENT '数据表',
    column_name VARCHAR(256) NULL COMMENT '字段',
    rule_scope VARCHAR(20) NOT NULL COMMENT 'TABLE/COLUMN',
    rule_type VARCHAR(40) NOT NULL COMMENT '规则类型',
    quality_dimension VARCHAR(40) NOT NULL COMMENT '质量维度',
    comparison_operator VARCHAR(20) NOT NULL COMMENT '比较符',
    threshold_value DECIMAL(30, 10) NOT NULL COMMENT '阈值',
    threshold_end DECIMAL(30, 10) NULL COMMENT '区间最大值',
    unit VARCHAR(20) NULL COMMENT '指标单位',
    schedule_mode VARCHAR(20) NOT NULL COMMENT 'MANUAL/SCHEDULE',
    schedule_preset VARCHAR(40) NULL COMMENT '调度预设',
    cron_expression VARCHAR(128) NULL COMMENT 'Cron 表达式',
    enabled TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否启用',
    custom_sql TEXT NULL COMMENT '自定义检查 SQL',
    config_json TEXT NULL COMMENT '规则扩展参数',
    last_result VARCHAR(20) NOT NULL DEFAULT 'NOT_RUN' COMMENT '最近检查结果',
    last_metric VARCHAR(128) NULL COMMENT '最近指标值',
    last_run_time DATETIME(3) NULL COMMENT '最近运行时间',
    last_duration_ms BIGINT NULL COMMENT '最近执行耗时',
    owner VARCHAR(128) NOT NULL COMMENT '负责人',
    deleted TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除',
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
        ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    KEY idx_yak_quality_rule_source (data_source_id, deleted),
    KEY idx_yak_quality_rule_type (rule_type, deleted),
    KEY idx_yak_quality_rule_enabled (enabled, deleted),
    KEY idx_yak_quality_rule_result (last_result, deleted),
    KEY idx_yak_quality_rule_updated (updated_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  COMMENT='数据质量规则';
