CREATE TABLE IF NOT EXISTS yak_quality_execution (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '执行内部编号',
    execution_no VARCHAR(64) NOT NULL COMMENT '执行编号',
    rule_id BIGINT NOT NULL COMMENT '质量规则编号',
    rule_name VARCHAR(80) NOT NULL COMMENT '规则名称快照',
    data_source_id VARCHAR(64) NOT NULL COMMENT '数据源编号快照',
    data_source_name VARCHAR(128) NOT NULL COMMENT '数据源名称快照',
    catalog_name VARCHAR(128) NULL COMMENT 'Catalog 名称快照',
    schema_name VARCHAR(128) NULL COMMENT 'Schema 名称快照',
    database_name VARCHAR(128) NOT NULL COMMENT '数据库展示名称快照',
    table_name VARCHAR(256) NOT NULL COMMENT '数据表快照',
    column_name VARCHAR(256) NULL COMMENT '字段快照',
    object_name VARCHAR(768) NOT NULL COMMENT '检查对象展示名称',
    rule_type VARCHAR(40) NOT NULL COMMENT '规则类型快照',
    comparison_operator VARCHAR(20) NOT NULL COMMENT '比较符快照',
    threshold_value DECIMAL(30, 10) NOT NULL COMMENT '阈值快照',
    threshold_end DECIMAL(30, 10) NULL COMMENT '区间最大值快照',
    unit VARCHAR(20) NULL COMMENT '指标单位快照',
    custom_sql MEDIUMTEXT NULL COMMENT '自定义 SQL 快照',
    trigger_type VARCHAR(20) NOT NULL COMMENT 'MANUAL/SCHEDULE',
    execution_status VARCHAR(20) NOT NULL DEFAULT 'WAITING'
        COMMENT 'WAITING/RUNNING/SUCCESS/FAILED',
    check_result VARCHAR(20) NOT NULL DEFAULT 'UNKNOWN'
        COMMENT 'PASSED/NOT_PASSED/UNKNOWN',
    metric_value DECIMAL(30, 10) NULL COMMENT '指标数值',
    metric_value_end DECIMAL(30, 10) NULL COMMENT '区间指标最大值',
    metric_display VARCHAR(256) NULL COMMENT '指标展示值',
    expected_display VARCHAR(256) NOT NULL COMMENT '期望值展示',
    executed_sql MEDIUMTEXT NULL COMMENT '最终执行 SQL',
    error_message VARCHAR(1000) NULL COMMENT '执行错误信息',
    operator_name VARCHAR(128) NOT NULL COMMENT '触发人',
    queued_at DATETIME(3) NOT NULL COMMENT '进入队列时间',
    started_at DATETIME(3) NULL COMMENT '开始时间',
    finished_at DATETIME(3) NULL COMMENT '结束时间',
    duration_ms BIGINT NULL COMMENT '执行耗时',
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
        ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uk_yak_quality_execution_no (execution_no),
    KEY idx_yak_quality_execution_rule (rule_id, created_at),
    KEY idx_yak_quality_execution_status (execution_status, created_at),
    KEY idx_yak_quality_execution_result (check_result, created_at),
    KEY idx_yak_quality_execution_trigger (trigger_type, created_at),
    KEY idx_yak_quality_execution_created (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  COMMENT='数据质量规则执行记录';
