package io.yak.ops.application.client.port;

import java.util.List;
import java.util.Map;

/**
 * Gateway interface for accessing LinkUp client runtime capabilities.
 *
 * <p>This port belongs to the core client module and only defines runtime operations
 * required by the upper application layer. The actual implementation can be based on
 * LinkUp REST API, SDK, or other communication mechanisms.</p>
 */
public interface LinkUpClientRuntimeGateway {

    /**
     * Queries runtime metrics of the specified LinkUp client.
     *
     * @param clientId LinkUp client id
     * @return raw runtime metrics returned by the engine
     */
    List<Map<String, Object>> metrics(Long clientId);

    /**
     * Queries job logs from the LinkUp engine.
     *
     * @param clientId LinkUp client id
     * @param engineJobId job id generated by the LinkUp engine
     * @param format log response format, such as json or text
     * @return engine job log content
     */
    String jobLogs(Long clientId, String engineJobId, String format);

    /**
     * Queries checkpoint overview of a LinkUp job.
     *
     * @param clientId LinkUp client id
     * @param jobId LinkUp engine job id
     * @return checkpoint overview information
     */
    Map<String, Object> checkpointOverview(Long clientId, Long jobId);

    /**
     * Queries checkpoint history of a LinkUp job.
     *
     * @param clientId LinkUp client id
     * @param jobId LinkUp engine job id
     * @param pipelineId optional pipeline id
     * @param limit max history size
     * @param status optional checkpoint status filter
     * @return checkpoint history list
     */
    List<Map<String, Object>> checkpointHistory(
            Long clientId,
            Long jobId,
            Long pipelineId,
            Integer limit,
            String status
    );
}
