import type {
  QualityExecutionRecord,
  QualityRule,
  QualityRuleType,
} from './types';

export const QUALITY_RULE_TYPE_META: Record<
  QualityRuleType,
  { label: string; dimension: string; scope: 'TABLE' | 'COLUMN'; unit?: string }
> = {
  TABLE_ROW_COUNT: {
    label: '表行数',
    dimension: '完整性',
    scope: 'TABLE',
    unit: '行',
  },
  COLUMN_NOT_NULL: {
    label: '字段非空率',
    dimension: '完整性',
    scope: 'COLUMN',
    unit: '%',
  },
  COLUMN_UNIQUE: {
    label: '字段唯一率',
    dimension: '唯一性',
    scope: 'COLUMN',
    unit: '%',
  },
  COLUMN_RANGE: {
    label: '数值范围',
    dimension: '有效性',
    scope: 'COLUMN',
  },
  DATA_FRESHNESS: {
    label: '数据新鲜度',
    dimension: '及时性',
    scope: 'COLUMN',
    unit: '小时',
  },
  CUSTOM_SQL: {
    label: '自定义 SQL',
    dimension: '自定义',
    scope: 'TABLE',
  },
};

export const DATA_SOURCE_OPTIONS = [
  { label: '生产 MySQL', value: 'ds-mysql-prod' },
  { label: '订单 PostgreSQL', value: 'ds-pg-order' },
  { label: '分析 Doris', value: 'ds-doris-bi' },
];

export const DATABASE_OPTIONS = [
  { label: 'yak_ops', value: 'yak_ops' },
  { label: 'order_center', value: 'order_center' },
  { label: 'analytics', value: 'analytics' },
];

export const TABLE_OPTIONS = [
  { label: 'user_info', value: 'user_info' },
  { label: 'order_info', value: 'order_info' },
  { label: 'payment_detail', value: 'payment_detail' },
  { label: 'dwd_order_daily', value: 'dwd_order_daily' },
];

export const COLUMN_OPTIONS = [
  { label: 'id', value: 'id' },
  { label: 'phone', value: 'phone' },
  { label: 'id_card', value: 'id_card' },
  { label: 'pay_amount', value: 'pay_amount' },
  { label: 'update_time', value: 'update_time' },
];

export const MOCK_QUALITY_RULES: QualityRule[] = [
  {
    id: 'QR-1008',
    name: '订单表每日必须有数据',
    description: '避免上游同步异常导致订单明细断流。',
    dataSourceId: 'ds-pg-order',
    dataSourceName: '订单 PostgreSQL',
    databaseName: 'order_center',
    tableName: 'order_info',
    scope: 'TABLE',
    ruleType: 'TABLE_ROW_COUNT',
    dimension: '完整性',
    operator: '>',
    threshold: 0,
    unit: '行',
    scheduleMode: 'SCHEDULE',
    scheduleLabel: '每天 02:00',
    cronExpression: '0 0 2 * * ?',
    enabled: true,
    importance: 'IMPORTANT',
    lastResult: 'PASSED',
    lastMetric: '128,436 行',
    lastRunTime: '2026-08-04 02:00:08',
    duration: 1268,
    owner: '魏福万',
  },
  {
    id: 'QR-1007',
    name: '用户手机号非空率',
    description: '保障客户联系信息完整。',
    dataSourceId: 'ds-mysql-prod',
    dataSourceName: '生产 MySQL',
    databaseName: 'yak_ops',
    tableName: 'user_info',
    columnName: 'phone',
    scope: 'COLUMN',
    ruleType: 'COLUMN_NOT_NULL',
    dimension: '完整性',
    operator: '>=',
    threshold: 99,
    unit: '%',
    scheduleMode: 'SCHEDULE',
    scheduleLabel: '每天 03:00',
    cronExpression: '0 0 3 * * ?',
    enabled: true,
    importance: 'IMPORTANT',
    lastResult: 'NOT_PASSED',
    lastMetric: '97.82%',
    lastRunTime: '2026-08-04 03:00:13',
    duration: 846,
    owner: '魏福万',
  },
  {
    id: 'QR-1006',
    name: '身份证号唯一率',
    description: '识别重复客户主数据。',
    dataSourceId: 'ds-mysql-prod',
    dataSourceName: '生产 MySQL',
    databaseName: 'yak_ops',
    tableName: 'user_info',
    columnName: 'id_card',
    scope: 'COLUMN',
    ruleType: 'COLUMN_UNIQUE',
    dimension: '唯一性',
    operator: '=',
    threshold: 100,
    unit: '%',
    scheduleMode: 'MANUAL',
    scheduleLabel: '仅手动执行',
    enabled: true,
    importance: 'NORMAL',
    lastResult: 'PASSED',
    lastMetric: '100%',
    lastRunTime: '2026-08-03 17:42:31',
    duration: 631,
    owner: '魏福万',
  },
  {
    id: 'QR-1005',
    name: '支付金额范围检查',
    description: '支付金额不能为负数。',
    dataSourceId: 'ds-pg-order',
    dataSourceName: '订单 PostgreSQL',
    databaseName: 'order_center',
    tableName: 'payment_detail',
    columnName: 'pay_amount',
    scope: 'COLUMN',
    ruleType: 'COLUMN_RANGE',
    dimension: '有效性',
    operator: '>=',
    threshold: 0,
    unit: '元',
    scheduleMode: 'SCHEDULE',
    scheduleLabel: '每小时',
    cronExpression: '0 0 * * * ?',
    enabled: true,
    importance: 'IMPORTANT',
    lastResult: 'ERROR',
    lastRunTime: '2026-08-04 19:00:02',
    duration: 30012,
    owner: '魏福万',
  },
  {
    id: 'QR-1004',
    name: '订单数据新鲜度',
    description: '订单更新时间与当前时间差不得超过 2 小时。',
    dataSourceId: 'ds-pg-order',
    dataSourceName: '订单 PostgreSQL',
    databaseName: 'order_center',
    tableName: 'order_info',
    columnName: 'update_time',
    scope: 'COLUMN',
    ruleType: 'DATA_FRESHNESS',
    dimension: '及时性',
    operator: '<=',
    threshold: 2,
    unit: '小时',
    scheduleMode: 'SCHEDULE',
    scheduleLabel: '每 30 分钟',
    cronExpression: '0 0/30 * * * ?',
    enabled: true,
    importance: 'IMPORTANT',
    lastResult: 'RUNNING',
    lastRunTime: '2026-08-04 20:30:00',
    owner: '魏福万',
  },
  {
    id: 'QR-1003',
    name: 'DWD 订单异常状态检查',
    description: '通过自定义 SQL 识别无法映射的订单状态。',
    dataSourceId: 'ds-doris-bi',
    dataSourceName: '分析 Doris',
    databaseName: 'analytics',
    tableName: 'dwd_order_daily',
    scope: 'TABLE',
    ruleType: 'CUSTOM_SQL',
    dimension: '自定义',
    operator: '=',
    threshold: 0,
    unit: '行',
    scheduleMode: 'MANUAL',
    scheduleLabel: '仅手动执行',
    enabled: false,
    importance: 'NORMAL',
    lastResult: 'NOT_RUN',
    owner: '魏福万',
    customSql:
      "SELECT COUNT(*) AS metric_value FROM analytics.dwd_order_daily WHERE order_status NOT IN ('CREATED', 'PAID', 'CLOSED')",
  },
];

export const MOCK_QUALITY_EXECUTIONS: QualityExecutionRecord[] = [
  {
    id: 'QE-20260804-0068',
    ruleId: 'QR-1007',
    ruleName: '用户手机号非空率',
    dataSourceName: '生产 MySQL',
    objectName: 'yak_ops.user_info.phone',
    ruleType: 'COLUMN_NOT_NULL',
    triggerType: 'SCHEDULE',
    executionStatus: 'SUCCESS',
    checkResult: 'NOT_PASSED',
    metricValue: '97.82%',
    expectedValue: '>= 99%',
    startedAt: '2026-08-04 03:00:13',
    finishedAt: '2026-08-04 03:00:14',
    duration: 846,
    operator: 'yak-schedule',
    sql: 'SELECT COUNT(*) AS total_count, SUM(CASE WHEN phone IS NULL OR phone = \'\' THEN 1 ELSE 0 END) AS null_count FROM yak_ops.user_info',
  },
  {
    id: 'QE-20260804-0067',
    ruleId: 'QR-1008',
    ruleName: '订单表每日必须有数据',
    dataSourceName: '订单 PostgreSQL',
    objectName: 'order_center.order_info',
    ruleType: 'TABLE_ROW_COUNT',
    triggerType: 'SCHEDULE',
    executionStatus: 'SUCCESS',
    checkResult: 'PASSED',
    metricValue: '128,436 行',
    expectedValue: '> 0 行',
    startedAt: '2026-08-04 02:00:08',
    finishedAt: '2026-08-04 02:00:09',
    duration: 1268,
    operator: 'yak-schedule',
    sql: 'SELECT COUNT(*) AS metric_value FROM order_center.order_info',
  },
  {
    id: 'QE-20260804-0066',
    ruleId: 'QR-1005',
    ruleName: '支付金额范围检查',
    dataSourceName: '订单 PostgreSQL',
    objectName: 'order_center.payment_detail.pay_amount',
    ruleType: 'COLUMN_RANGE',
    triggerType: 'SCHEDULE',
    executionStatus: 'FAILED',
    checkResult: 'UNKNOWN',
    expectedValue: '>= 0 元',
    startedAt: '2026-08-04 19:00:02',
    finishedAt: '2026-08-04 19:00:32',
    duration: 30012,
    operator: 'yak-schedule',
    sql: 'SELECT MIN(pay_amount) AS metric_value FROM order_center.payment_detail',
    errorMessage: '查询执行超时，请检查数据源负载或适当调大规则超时时间。',
  },
  {
    id: 'QE-20260804-0065',
    ruleId: 'QR-1004',
    ruleName: '订单数据新鲜度',
    dataSourceName: '订单 PostgreSQL',
    objectName: 'order_center.order_info.update_time',
    ruleType: 'DATA_FRESHNESS',
    triggerType: 'SCHEDULE',
    executionStatus: 'RUNNING',
    checkResult: 'UNKNOWN',
    expectedValue: '<= 2 小时',
    startedAt: '2026-08-04 20:30:00',
    operator: 'yak-schedule',
    sql: 'SELECT MAX(update_time) AS metric_value FROM order_center.order_info',
  },
  {
    id: 'QE-20260803-0064',
    ruleId: 'QR-1006',
    ruleName: '身份证号唯一率',
    dataSourceName: '生产 MySQL',
    objectName: 'yak_ops.user_info.id_card',
    ruleType: 'COLUMN_UNIQUE',
    triggerType: 'MANUAL',
    executionStatus: 'SUCCESS',
    checkResult: 'PASSED',
    metricValue: '100%',
    expectedValue: '= 100%',
    startedAt: '2026-08-03 17:42:31',
    finishedAt: '2026-08-03 17:42:32',
    duration: 631,
    operator: '魏福万',
    sql: 'SELECT COUNT(DISTINCT id_card) / COUNT(id_card) * 100 AS metric_value FROM yak_ops.user_info WHERE id_card IS NOT NULL',
  },
];
